/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { OfficeRoleConfig } from "./officeRoleConfig.ts";
import type { ColumnType } from "kysely";

export type AuthAalLevel = "aal1" | "aal2" | "aal3";

export type AuthCodeChallengeMethod = "plain" | "s256";

export type AuthFactorStatus = "unverified" | "verified";

export type AuthFactorType = "phone" | "totp" | "webauthn";

export type AuthOauthAuthorizationStatus = "approved" | "denied" | "expired" | "pending";

export type AuthOauthClientType = "confidential" | "public";

export type AuthOauthRegistrationType = "dynamic" | "manual";

export type AuthOauthResponseType = "code";

export type AuthOneTimeTokenType = "confirmation_token" | "email_change_token_current" | "email_change_token_new" | "phone_change_token" | "reauthentication_token" | "recovery_token";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type StorageBuckettype = "ANALYTICS" | "STANDARD" | "VECTOR";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _AuditLog {
  audit_log_id: Generated<Int8>;
  changed_at: Generated<Timestamp>;
  changed_by: string;
  diff: Json;
  op: string;
  record_pk: Json;
  table_name: string;
  table_schema: string;
}

export interface _Employees {
  bar_numbers: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string;
  dashboard_roles: Generated<string[]>;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  full_legal_name: string;
  office_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  user_id: string;
}

export interface _Entities {
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  email: string | null;
  entity_id: Generated<string>;
  entity_type: Generated<string>;
  full_legal_name: string;
  metadata: Generated<Json>;
  office_id: string;
  phone: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  user_id: string | null;
}

export interface _EntityRoles {
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  entity_id: string;
  matter_id: string;
  office_id: string;
  role: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface _Expenses {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  description: string | null;
  expense_id: Generated<string>;
  external_invoice_data: Generated<Json>;
  invoice_id: string | null;
  is_billable: Generated<boolean>;
  is_reimbursable: Generated<boolean>;
  matter_id: string | null;
  office_id: string;
  receipt_path: Generated<string[]>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface _Forms {
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  entity_id: string;
  form_data: Generated<Json>;
  form_id: Generated<string>;
  form_type: string;
  matter_id: string | null;
  office_id: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface _InvoicePayments {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  external_data: Generated<Json>;
  external_id: string | null;
  external_type: string | null;
  external_url: string | null;
  invoice_id: string | null;
  invoice_payment_id: Generated<string>;
  notes: string | null;
  office_id: string;
  payment_date: Timestamp;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface _Invoices {
  billed_amount: Numeric;
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  due_date: Timestamp | null;
  invoice_id: Generated<string>;
  late_fee_amount: Generated<Numeric>;
  late_fee_rate: Numeric;
  matter_id: string | null;
  notes: string | null;
  office_id: string;
  sent_at: Timestamp | null;
  status: Generated<string>;
  total_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface _Leads {
  assigned_attorney_user_id: string | null;
  conflict_check_passed_at: Timestamp | null;
  conflict_check_passed_by: string | null;
  conflict_search_results: Generated<Json>;
  consultation_scheduled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  email: string | null;
  entity_id: string | null;
  entity_search_results: Generated<Json>;
  existing_entity_check_passed_at: Timestamp | null;
  existing_entity_check_passed_by: string | null;
  existing_entity_id: string | null;
  fee_agreement_status: string | null;
  full_legal_name: string | null;
  lead_id: Generated<string>;
  lead_source: string | null;
  lead_source_data: Generated<Json>;
  matter_data: Generated<Json>;
  matter_id: string | null;
  matter_type: string | null;
  office_id: string;
  opposing_party_names: Generated<Json>;
  other_entity_names: Generated<Json>;
  phone: string | null;
  score: Numeric | null;
  stage: Generated<string>;
  suggested_attorney_user_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface _Matters {
  archived_at: Timestamp | null;
  archived_by: string | null;
  billing_settings: Generated<Json>;
  billing_type: Generated<string>;
  created_at: Generated<Timestamp>;
  created_by: string;
  data: Generated<Json>;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  description: Generated<string>;
  ended_representation_at: Timestamp | null;
  matter_id: Generated<string>;
  office_id: string;
  preferred_office_location: Generated<string>;
  referral_data: Generated<Json>;
  referral_id: string | null;
  referral_source: string | null;
  stage: Generated<string>;
  started_representation_at: Timestamp | null;
  title: string;
  type: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface _MatterStaff {
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  matter_id: string;
  office_id: string;
  role: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  user_id: string;
}

export interface _Offices {
  address: Json | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  email: string | null;
  logo: string | null;
  name: string;
  office_id: Generated<string>;
  phone: string | null;
  role_config: OfficeRoleConfig;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  website: string | null;
}

export interface _RealtimeExtensions {
  id: string;
  inserted_at: Timestamp;
  settings: Json | null;
  tenant_external_id: string | null;
  type: string | null;
  updated_at: Timestamp;
}

export interface _RealtimeSchemaMigrations {
  inserted_at: Timestamp | null;
  version: Int8;
}

export interface _RealtimeTenants {
  broadcast_adapter: Generated<string | null>;
  external_id: string | null;
  id: string;
  inserted_at: Timestamp;
  jwt_jwks: Json | null;
  jwt_secret: string | null;
  max_bytes_per_second: Generated<number>;
  max_channels_per_client: Generated<number>;
  max_concurrent_users: Generated<number>;
  max_events_per_second: Generated<number>;
  max_joins_per_second: Generated<number>;
  max_payload_size_in_kb: Generated<number | null>;
  max_presence_events_per_second: Generated<number | null>;
  migrations_ran: Generated<number | null>;
  name: string | null;
  notify_private_alpha: Generated<boolean | null>;
  postgres_cdc_default: Generated<string | null>;
  private_only: Generated<boolean>;
  suspend: Generated<boolean | null>;
  updated_at: Timestamp;
}

export interface _Tasks {
  assigned_to: string | null;
  billable: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  description: Generated<string>;
  due_date: Timestamp | null;
  lead_id: string | null;
  matter_id: string | null;
  name: string;
  no_charge: Generated<boolean>;
  office_id: string;
  status: Generated<string>;
  task_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface _TimeEntries {
  actual_duration: number;
  billable_duration: number;
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  description: string | null;
  end_timestamp: Timestamp;
  invoice_id: string | null;
  office_id: string;
  task_id: string | null;
  time_entry_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  user_id: string;
}

export interface _UserProfiles {
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  display_name: string;
  email: string;
  phone: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  user_id: string;
}

export interface AuthAuditLogEntries {
  created_at: Timestamp | null;
  id: string;
  instance_id: string | null;
  ip_address: Generated<string>;
  payload: Json | null;
}

export interface AuthCustomOauthProviders {
  acceptable_client_ids: Generated<string[]>;
  attribute_mapping: Generated<Json>;
  authorization_params: Generated<Json>;
  authorization_url: string | null;
  cached_discovery: Json | null;
  client_id: string;
  client_secret: string;
  created_at: Generated<Timestamp>;
  discovery_cached_at: Timestamp | null;
  discovery_url: string | null;
  email_optional: Generated<boolean>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  identifier: string;
  issuer: string | null;
  jwks_uri: string | null;
  name: string;
  pkce_enabled: Generated<boolean>;
  provider_type: string;
  scopes: Generated<string[]>;
  skip_nonce_check: Generated<boolean>;
  token_url: string | null;
  updated_at: Generated<Timestamp>;
  userinfo_url: string | null;
}

export interface AuthFlowState {
  auth_code: string | null;
  auth_code_issued_at: Timestamp | null;
  authentication_method: string;
  code_challenge: string | null;
  code_challenge_method: AuthCodeChallengeMethod | null;
  created_at: Timestamp | null;
  email_optional: Generated<boolean>;
  id: string;
  invite_token: string | null;
  linking_target_id: string | null;
  oauth_client_state_id: string | null;
  provider_access_token: string | null;
  provider_refresh_token: string | null;
  provider_type: string;
  referrer: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface AuthIdentities {
  created_at: Timestamp | null;
  /**
   * Auth: Email is a generated column that references the optional email property in the identity_data
   */
  email: Generated<string | null>;
  id: Generated<string>;
  identity_data: Json;
  last_sign_in_at: Timestamp | null;
  provider: string;
  provider_id: string;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface AuthInstances {
  created_at: Timestamp | null;
  id: string;
  raw_base_config: string | null;
  updated_at: Timestamp | null;
  uuid: string | null;
}

export interface AuthMfaAmrClaims {
  authentication_method: string;
  created_at: Timestamp;
  id: string;
  session_id: string;
  updated_at: Timestamp;
}

export interface AuthMfaChallenges {
  created_at: Timestamp;
  factor_id: string;
  id: string;
  ip_address: string;
  otp_code: string | null;
  verified_at: Timestamp | null;
  web_authn_session_data: Json | null;
}

export interface AuthMfaFactors {
  created_at: Timestamp;
  factor_type: AuthFactorType;
  friendly_name: string | null;
  id: string;
  last_challenged_at: Timestamp | null;
  /**
   * Stores the latest WebAuthn challenge data including attestation/assertion for customer verification
   */
  last_webauthn_challenge_data: Json | null;
  phone: string | null;
  secret: string | null;
  status: AuthFactorStatus;
  updated_at: Timestamp;
  user_id: string;
  web_authn_aaguid: string | null;
  web_authn_credential: Json | null;
}

export interface AuthOauthAuthorizations {
  approved_at: Timestamp | null;
  authorization_code: string | null;
  authorization_id: string;
  client_id: string;
  code_challenge: string | null;
  code_challenge_method: AuthCodeChallengeMethod | null;
  created_at: Generated<Timestamp>;
  expires_at: Generated<Timestamp>;
  id: string;
  nonce: string | null;
  redirect_uri: string;
  resource: string | null;
  response_type: Generated<AuthOauthResponseType>;
  scope: string;
  state: string | null;
  status: Generated<AuthOauthAuthorizationStatus>;
  user_id: string | null;
}

export interface AuthOauthClients {
  client_name: string | null;
  client_secret_hash: string | null;
  client_type: Generated<AuthOauthClientType>;
  client_uri: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  grant_types: string;
  id: string;
  logo_uri: string | null;
  redirect_uris: string;
  registration_type: AuthOauthRegistrationType;
  token_endpoint_auth_method: string;
  updated_at: Generated<Timestamp>;
}

export interface AuthOauthClientStates {
  code_verifier: string | null;
  created_at: Timestamp;
  id: string;
  provider_type: string;
}

export interface AuthOauthConsents {
  client_id: string;
  granted_at: Generated<Timestamp>;
  id: string;
  revoked_at: Timestamp | null;
  scopes: string;
  user_id: string;
}

export interface AuthOneTimeTokens {
  created_at: Generated<Timestamp>;
  id: string;
  relates_to: string;
  token_hash: string;
  token_type: AuthOneTimeTokenType;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthRefreshTokens {
  created_at: Timestamp | null;
  id: Generated<Int8>;
  instance_id: string | null;
  parent: string | null;
  revoked: boolean | null;
  session_id: string | null;
  token: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface AuthSamlProviders {
  attribute_mapping: Json | null;
  created_at: Timestamp | null;
  entity_id: string;
  id: string;
  metadata_url: string | null;
  metadata_xml: string;
  name_id_format: string | null;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSamlRelayStates {
  created_at: Timestamp | null;
  flow_state_id: string | null;
  for_email: string | null;
  id: string;
  redirect_to: string | null;
  request_id: string;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSchemaMigrations {
  version: string;
}

export interface AuthSessions {
  aal: AuthAalLevel | null;
  created_at: Timestamp | null;
  factor_id: string | null;
  id: string;
  ip: string | null;
  /**
   * Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired.
   */
  not_after: Timestamp | null;
  oauth_client_id: string | null;
  /**
   * Holds the ID (counter) of the last issued refresh token.
   */
  refresh_token_counter: Int8 | null;
  /**
   * Holds a HMAC-SHA256 key used to sign refresh tokens for this session.
   */
  refresh_token_hmac_key: string | null;
  refreshed_at: Timestamp | null;
  scopes: string | null;
  tag: string | null;
  updated_at: Timestamp | null;
  user_agent: string | null;
  user_id: string;
}

export interface AuthSsoDomains {
  created_at: Timestamp | null;
  domain: string;
  id: string;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSsoProviders {
  created_at: Timestamp | null;
  disabled: boolean | null;
  id: string;
  /**
   * Auth: Uniquely identifies a SSO provider according to a user-chosen resource ID (case insensitive), useful in infrastructure as code.
   */
  resource_id: string | null;
  updated_at: Timestamp | null;
}

export interface AuthUsers {
  aud: string | null;
  banned_until: Timestamp | null;
  confirmation_sent_at: Timestamp | null;
  confirmation_token: string | null;
  confirmed_at: Generated<Timestamp | null>;
  created_at: Timestamp | null;
  deleted_at: Timestamp | null;
  email: string | null;
  email_change: string | null;
  email_change_confirm_status: Generated<number | null>;
  email_change_sent_at: Timestamp | null;
  email_change_token_current: Generated<string | null>;
  email_change_token_new: string | null;
  email_confirmed_at: Timestamp | null;
  encrypted_password: string | null;
  id: string;
  instance_id: string | null;
  invited_at: Timestamp | null;
  is_anonymous: Generated<boolean>;
  /**
   * Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.
   */
  is_sso_user: Generated<boolean>;
  is_super_admin: boolean | null;
  last_sign_in_at: Timestamp | null;
  phone: Generated<string | null>;
  phone_change: Generated<string | null>;
  phone_change_sent_at: Timestamp | null;
  phone_change_token: Generated<string | null>;
  phone_confirmed_at: Timestamp | null;
  raw_app_meta_data: Json | null;
  raw_user_meta_data: Json | null;
  reauthentication_sent_at: Timestamp | null;
  reauthentication_token: Generated<string | null>;
  recovery_sent_at: Timestamp | null;
  recovery_token: string | null;
  role: string | null;
  updated_at: Timestamp | null;
}

export interface Employees {
  bar_numbers: Json | null;
  created_at: Timestamp | null;
  created_by: string | null;
  dashboard_roles: string[] | null;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  full_legal_name: string | null;
  office_id: string | null;
  updated_at: Timestamp | null;
  updated_by: string | null;
  user_id: string | null;
}

export interface Entities {
  created_at: Timestamp | null;
  created_by: string | null;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  email: string | null;
  entity_id: string | null;
  entity_type: string | null;
  full_legal_name: string | null;
  metadata: Json | null;
  office_id: string | null;
  phone: string | null;
  updated_at: Timestamp | null;
  updated_by: string | null;
  user_id: string | null;
}

export interface EntityRoles {
  created_at: Timestamp | null;
  created_by: string | null;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  entity_id: string | null;
  matter_id: string | null;
  office_id: string | null;
  role: string | null;
  updated_at: Timestamp | null;
  updated_by: string | null;
}

export interface Expenses {
  amount: Numeric | null;
  created_at: Timestamp | null;
  created_by: string | null;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  description: string | null;
  expense_id: string | null;
  external_invoice_data: Json | null;
  invoice_id: string | null;
  is_billable: boolean | null;
  is_reimbursable: boolean | null;
  matter_id: string | null;
  office_id: string | null;
  receipt_path: string[] | null;
  updated_at: Timestamp | null;
  updated_by: string | null;
}

export interface ExtensionsPgStatStatements {
  calls: Int8 | null;
  dbid: number | null;
  jit_deform_count: Int8 | null;
  jit_deform_time: number | null;
  jit_emission_count: Int8 | null;
  jit_emission_time: number | null;
  jit_functions: Int8 | null;
  jit_generation_time: number | null;
  jit_inlining_count: Int8 | null;
  jit_inlining_time: number | null;
  jit_optimization_count: Int8 | null;
  jit_optimization_time: number | null;
  local_blk_read_time: number | null;
  local_blk_write_time: number | null;
  local_blks_dirtied: Int8 | null;
  local_blks_hit: Int8 | null;
  local_blks_read: Int8 | null;
  local_blks_written: Int8 | null;
  max_exec_time: number | null;
  max_plan_time: number | null;
  mean_exec_time: number | null;
  mean_plan_time: number | null;
  min_exec_time: number | null;
  min_plan_time: number | null;
  minmax_stats_since: Timestamp | null;
  plans: Int8 | null;
  query: string | null;
  queryid: Int8 | null;
  rows: Int8 | null;
  shared_blk_read_time: number | null;
  shared_blk_write_time: number | null;
  shared_blks_dirtied: Int8 | null;
  shared_blks_hit: Int8 | null;
  shared_blks_read: Int8 | null;
  shared_blks_written: Int8 | null;
  stats_since: Timestamp | null;
  stddev_exec_time: number | null;
  stddev_plan_time: number | null;
  temp_blk_read_time: number | null;
  temp_blk_write_time: number | null;
  temp_blks_read: Int8 | null;
  temp_blks_written: Int8 | null;
  toplevel: boolean | null;
  total_exec_time: number | null;
  total_plan_time: number | null;
  userid: number | null;
  wal_bytes: Numeric | null;
  wal_fpi: Int8 | null;
  wal_records: Int8 | null;
}

export interface ExtensionsPgStatStatementsInfo {
  dealloc: Int8 | null;
  stats_reset: Timestamp | null;
}

export interface Forms {
  created_at: Timestamp | null;
  created_by: string | null;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  entity_id: string | null;
  form_data: Json | null;
  form_id: string | null;
  form_type: string | null;
  matter_id: string | null;
  office_id: string | null;
  status: string | null;
  updated_at: Timestamp | null;
  updated_by: string | null;
}

export interface InvoicePayments {
  amount: Numeric | null;
  created_at: Timestamp | null;
  created_by: string | null;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  external_data: Json | null;
  external_id: string | null;
  external_type: string | null;
  external_url: string | null;
  invoice_id: string | null;
  invoice_payment_id: string | null;
  notes: string | null;
  office_id: string | null;
  payment_date: Timestamp | null;
  updated_at: Timestamp | null;
  updated_by: string | null;
}

export interface Invoices {
  billed_amount: Numeric | null;
  created_at: Timestamp | null;
  created_by: string | null;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  due_date: Timestamp | null;
  invoice_id: string | null;
  late_fee_amount: Numeric | null;
  late_fee_rate: Numeric | null;
  matter_id: string | null;
  notes: string | null;
  office_id: string | null;
  sent_at: Timestamp | null;
  status: string | null;
  total_amount: Numeric | null;
  updated_at: Timestamp | null;
  updated_by: string | null;
}

export interface Leads {
  assigned_attorney_user_id: string | null;
  conflict_check_passed_at: Timestamp | null;
  conflict_check_passed_by: string | null;
  conflict_search_results: Json | null;
  consultation_scheduled_at: Timestamp | null;
  created_at: Timestamp | null;
  created_by: string | null;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  email: string | null;
  entity_id: string | null;
  entity_search_results: Json | null;
  existing_entity_check_passed_at: Timestamp | null;
  existing_entity_check_passed_by: string | null;
  existing_entity_id: string | null;
  fee_agreement_status: string | null;
  full_legal_name: string | null;
  lead_id: string | null;
  lead_source: string | null;
  lead_source_data: Json | null;
  matter_data: Json | null;
  matter_id: string | null;
  matter_type: string | null;
  office_id: string | null;
  opposing_party_names: Json | null;
  other_entity_names: Json | null;
  phone: string | null;
  score: Numeric | null;
  stage: string | null;
  suggested_attorney_user_id: string | null;
  updated_at: Timestamp | null;
  updated_by: string | null;
}

export interface Matters {
  archived_at: Timestamp | null;
  archived_by: string | null;
  billing_settings: Json | null;
  billing_type: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  data: Json | null;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  description: string | null;
  ended_representation_at: Timestamp | null;
  matter_id: string | null;
  office_id: string | null;
  preferred_office_location: string | null;
  referral_data: Json | null;
  referral_id: string | null;
  referral_source: string | null;
  stage: string | null;
  started_representation_at: Timestamp | null;
  title: string | null;
  type: string | null;
  updated_at: Timestamp | null;
  updated_by: string | null;
}

export interface MatterStaff {
  created_at: Timestamp | null;
  created_by: string | null;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  matter_id: string | null;
  office_id: string | null;
  role: string | null;
  updated_at: Timestamp | null;
  updated_by: string | null;
  user_id: string | null;
}

export interface NetHttpRequestQueue {
  body: Buffer | null;
  headers: Json | null;
  id: Generated<Int8>;
  method: string;
  timeout_milliseconds: number;
  url: string;
}

export interface NetHttpResponse {
  content: string | null;
  content_type: string | null;
  created: Generated<Timestamp>;
  error_msg: string | null;
  headers: Json | null;
  id: Int8 | null;
  status_code: number | null;
  timed_out: boolean | null;
}

export interface Offices {
  address: Json | null;
  created_at: Timestamp | null;
  created_by: string | null;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  email: string | null;
  logo: string | null;
  name: string | null;
  office_id: string | null;
  phone: string | null;
  role_config: OfficeRoleConfig;
  updated_at: Timestamp | null;
  updated_by: string | null;
  website: string | null;
}

export interface RealtimeMessages {
  event: string | null;
  extension: string;
  id: Generated<string>;
  inserted_at: Generated<Timestamp>;
  payload: Json | null;
  private: Generated<boolean | null>;
  topic: string;
  updated_at: Generated<Timestamp>;
}

export interface RealtimeSchemaMigrations {
  inserted_at: Timestamp | null;
  version: Int8;
}

export interface RealtimeSubscription {
  claims: Json;
  claims_role: Generated<string>;
  created_at: Generated<Timestamp>;
  entity: string;
  filters: Generated<string[]>;
  id: Generated<Int8>;
  subscription_id: string;
}

export interface StorageBuckets {
  allowed_mime_types: string[] | null;
  avif_autodetection: Generated<boolean | null>;
  created_at: Generated<Timestamp | null>;
  file_size_limit: Int8 | null;
  id: string;
  name: string;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  owner_id: string | null;
  public: Generated<boolean | null>;
  type: Generated<StorageBuckettype>;
  updated_at: Generated<Timestamp | null>;
}

export interface StorageBucketsAnalytics {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  format: Generated<string>;
  id: Generated<string>;
  name: string;
  type: Generated<StorageBuckettype>;
  updated_at: Generated<Timestamp>;
}

export interface StorageBucketsVectors {
  created_at: Generated<Timestamp>;
  id: string;
  type: Generated<StorageBuckettype>;
  updated_at: Generated<Timestamp>;
}

export interface StorageIcebergNamespaces {
  bucket_name: string;
  catalog_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Generated<Json>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface StorageIcebergTables {
  bucket_name: string;
  catalog_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  location: string;
  name: string;
  namespace_id: string;
  remote_table_id: string | null;
  shard_id: string | null;
  shard_key: string | null;
  updated_at: Generated<Timestamp>;
}

export interface StorageMigrations {
  executed_at: Generated<Timestamp | null>;
  hash: string;
  id: number;
  name: string;
}

export interface StorageObjects {
  bucket_id: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  last_accessed_at: Generated<Timestamp | null>;
  metadata: Json | null;
  name: string | null;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  owner_id: string | null;
  path_tokens: Generated<string[] | null>;
  updated_at: Generated<Timestamp | null>;
  user_metadata: Json | null;
  version: string | null;
}

export interface StorageS3MultipartUploads {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  in_progress_size: Generated<Int8>;
  key: string;
  owner_id: string | null;
  upload_signature: string;
  user_metadata: Json | null;
  version: string;
}

export interface StorageS3MultipartUploadsParts {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  etag: string;
  id: Generated<string>;
  key: string;
  owner_id: string | null;
  part_number: number;
  size: Generated<Int8>;
  upload_id: string;
  version: string;
}

export interface StorageVectorIndexes {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  data_type: string;
  dimension: number;
  distance_metric: string;
  id: Generated<string>;
  metadata_configuration: Json | null;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface SupabaseFunctionsHooks {
  created_at: Generated<Timestamp>;
  hook_name: string;
  hook_table_id: number;
  id: Generated<Int8>;
  request_id: Int8 | null;
}

export interface SupabaseFunctionsMigrations {
  inserted_at: Generated<Timestamp>;
  version: string;
}

export interface SupabaseMigrationsSchemaMigrations {
  name: string | null;
  statements: string[] | null;
  version: string;
}

export interface SupabaseMigrationsSeedFiles {
  hash: string;
  path: string;
}

export interface Tasks {
  assigned_to: string | null;
  billable: boolean | null;
  created_at: Timestamp | null;
  created_by: string | null;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  description: string | null;
  due_date: Timestamp | null;
  lead_id: string | null;
  matter_id: string | null;
  name: string | null;
  no_charge: boolean | null;
  office_id: string | null;
  status: string | null;
  task_id: string | null;
  updated_at: Timestamp | null;
  updated_by: string | null;
}

export interface TimeEntries {
  actual_duration: number | null;
  billable_duration: number | null;
  created_at: Timestamp | null;
  created_by: string | null;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  description: string | null;
  end_timestamp: Timestamp | null;
  invoice_id: string | null;
  office_id: string | null;
  task_id: string | null;
  time_entry_id: string | null;
  updated_at: Timestamp | null;
  updated_by: string | null;
  user_id: string | null;
}

export interface UserProfiles {
  created_at: Timestamp | null;
  created_by: string | null;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  display_name: string | null;
  email: string | null;
  phone: string | null;
  updated_at: Timestamp | null;
  updated_by: string | null;
  user_id: string | null;
}

export interface VaultDecryptedSecrets {
  created_at: Timestamp | null;
  decrypted_secret: string | null;
  description: string | null;
  id: string | null;
  key_id: string | null;
  name: string | null;
  nonce: Buffer | null;
  secret: string | null;
  updated_at: Timestamp | null;
}

export interface VaultSecrets {
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  id: Generated<string>;
  key_id: string | null;
  name: string | null;
  nonce: Generated<Buffer | null>;
  secret: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  _audit_log: _AuditLog;
  _employees: _Employees;
  _entities: _Entities;
  _entity_roles: _EntityRoles;
  _expenses: _Expenses;
  _forms: _Forms;
  _invoice_payments: _InvoicePayments;
  _invoices: _Invoices;
  _leads: _Leads;
  _matter_staff: _MatterStaff;
  _matters: _Matters;
  _offices: _Offices;
  "_realtime.extensions": _RealtimeExtensions;
  "_realtime.schema_migrations": _RealtimeSchemaMigrations;
  "_realtime.tenants": _RealtimeTenants;
  _tasks: _Tasks;
  _time_entries: _TimeEntries;
  _user_profiles: _UserProfiles;
  "auth.audit_log_entries": AuthAuditLogEntries;
  "auth.custom_oauth_providers": AuthCustomOauthProviders;
  "auth.flow_state": AuthFlowState;
  "auth.identities": AuthIdentities;
  "auth.instances": AuthInstances;
  "auth.mfa_amr_claims": AuthMfaAmrClaims;
  "auth.mfa_challenges": AuthMfaChallenges;
  "auth.mfa_factors": AuthMfaFactors;
  "auth.oauth_authorizations": AuthOauthAuthorizations;
  "auth.oauth_client_states": AuthOauthClientStates;
  "auth.oauth_clients": AuthOauthClients;
  "auth.oauth_consents": AuthOauthConsents;
  "auth.one_time_tokens": AuthOneTimeTokens;
  "auth.refresh_tokens": AuthRefreshTokens;
  "auth.saml_providers": AuthSamlProviders;
  "auth.saml_relay_states": AuthSamlRelayStates;
  "auth.schema_migrations": AuthSchemaMigrations;
  "auth.sessions": AuthSessions;
  "auth.sso_domains": AuthSsoDomains;
  "auth.sso_providers": AuthSsoProviders;
  "auth.users": AuthUsers;
  employees: Employees;
  entities: Entities;
  entity_roles: EntityRoles;
  expenses: Expenses;
  "extensions.pg_stat_statements": ExtensionsPgStatStatements;
  "extensions.pg_stat_statements_info": ExtensionsPgStatStatementsInfo;
  forms: Forms;
  invoice_payments: InvoicePayments;
  invoices: Invoices;
  leads: Leads;
  matter_staff: MatterStaff;
  matters: Matters;
  "net._http_response": NetHttpResponse;
  "net.http_request_queue": NetHttpRequestQueue;
  offices: Offices;
  "realtime.messages": RealtimeMessages;
  "realtime.schema_migrations": RealtimeSchemaMigrations;
  "realtime.subscription": RealtimeSubscription;
  "storage.buckets": StorageBuckets;
  "storage.buckets_analytics": StorageBucketsAnalytics;
  "storage.buckets_vectors": StorageBucketsVectors;
  "storage.iceberg_namespaces": StorageIcebergNamespaces;
  "storage.iceberg_tables": StorageIcebergTables;
  "storage.migrations": StorageMigrations;
  "storage.objects": StorageObjects;
  "storage.s3_multipart_uploads": StorageS3MultipartUploads;
  "storage.s3_multipart_uploads_parts": StorageS3MultipartUploadsParts;
  "storage.vector_indexes": StorageVectorIndexes;
  "supabase_functions.hooks": SupabaseFunctionsHooks;
  "supabase_functions.migrations": SupabaseFunctionsMigrations;
  "supabase_migrations.schema_migrations": SupabaseMigrationsSchemaMigrations;
  "supabase_migrations.seed_files": SupabaseMigrationsSeedFiles;
  tasks: Tasks;
  time_entries: TimeEntries;
  user_profiles: UserProfiles;
  "vault.decrypted_secrets": VaultDecryptedSecrets;
  "vault.secrets": VaultSecrets;
}
