import type { Insertable, Selectable } from "kysely";
import type { DB } from "./remappedDB";
import type { AuthUsers } from "./dbTypes";

export type Office = Selectable<DB["offices"]>;
export type Employee = Selectable<DB["employees"]>;
export type NewEmployee = Insertable<DB["employees"]>;
export type Matter = Selectable<DB["matters"]>;
export type NewMatter = Insertable<DB["matters"]>;
export type MatterStaffMember = Selectable<DB["matter_staff"]>;
export type NewMatterStaffMember = Insertable<DB["matter_staff"]>;
export type TimeEntry = Selectable<DB["time_entries"]>;
export type NewTimeEntry = Insertable<DB["time_entries"]>;
export type Lead = Selectable<DB["leads"]>;
export type NewLead = Insertable<DB["leads"]>;
export type Task = Selectable<DB["tasks"]>;
export type NewTask = Insertable<DB["tasks"]>;
export type Invoice = Selectable<DB["invoices"]>;
export type NewInvoice = Insertable<DB["invoices"]>;
export type Expense = Selectable<DB["expenses"]>;
export type NewExpense = Insertable<DB["expenses"]>;
export type InvoicePayment = Selectable<DB["invoice_payments"]>;
export type NewInvoicePayment = Insertable<DB["invoice_payments"]>;
export type Form = Selectable<DB["forms"]>;
export type NewForm = Insertable<DB["forms"]>;
export type AuthUser = Selectable<AuthUsers>;
